[package]
name = "skeptical"
version = "0.1.0"
authors = ["Matthew Mayer <matthewkmayer@gmail.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
env_logger = "0.5"
tokio = "0.2"


[dependencies.rusoto_core]
path = "../rusoto/core"
version = "0.43"
[dependencies.rusoto_dynamodb]
path = "../rusoto/services/dynamodb"
version = "0.43"
[dependencies.rusoto_s3]
path = "../rusoto/services/s3"
version = "0.43"
[dependencies.rusoto_ec2]
path = "../rusoto/services/ec2"
version = "0.43"
[dependencies.rusoto_sts]
path = "../rusoto/services/sts"
version = "0.43"


[build-dependencies]
skeptic = "0.13"

[dev-dependencies]
skeptic = "0.13" 
