# from https://github.com/japaric/rust-everywhere and https://github.com/yupferris/rustendo64/blob/master/appveyor.yml

os: Visual Studio 2015

environment:
  global:
    # This will be used as part of the zipfile name
    PROJECT_NAME: rusoto
  matrix:
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: stable
cache:
  - 'C:\Users\appveyor\.cargo'
# Install Rust and Cargo
# (Based on from https://github.com/rust-lang/libc/blob/master/appveyor.yml)
install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin;c:\cygwin\bin
  - rustc -Vv
  - cargo -V
  - git submodule update --init --recursive

# Equivalent to Travis' `script` phase
build_script:
  # https://github.com/sfackler/rust-openssl/issues/293
  - set DEP_OPENSSL_INCLUDE=C:\OpenSSL-Win64\include
  - set OPENSSL_INCLUDE_DIR=C:\OpenSSL-Win64\include
  - set OPENSSL_LIBS=ssleay32MT:libeay32MT
  - set OPENSSL_LIB_DIR=C:\OpenSSL-Win64\lib\VC
  - path C:\OpenSSL-Win64\bin;%PATH%
  - cargo test --lib --features "dynamodb s3 sqs"
  - ps: |
      $features = Select-String -Pattern "all =" -Path .\Cargo.toml | % { $_ -replace "\[","" -replace "\]","" -replace "=","" -replace ",","" } | %{ $_.split() }
      foreach ($feature in $features) { if ($feature.length -gt 0 -and $feature -notlike "*Cargo.toml*") { cargo build --features $feature } }

test_script:
  - ps: |
      $features = Select-String -Pattern "all =" -Path .\Cargo.toml | % { $_ -replace "\[","" -replace "\]","" -replace "=","" -replace ",","" } | %{ $_.split() }
      foreach ($feature in $features) { if ($feature.length -gt 0 -and $feature -notlike "*Cargo.toml*") { cargo test --lib --features $feature } }

branches:
  only:
    - master
