[package]
authors = [
    "Anthony DiMarco <ocramida@gmail.com>",
    "Jimmy Cuadra <jimmy@jimmycuadra.com>",
    "Matthew Mayer <matthewkmayer@gmail.com>",
    "Nikita Pekin <contact@nikitapek.in>"
]
build = "build.rs"
description = "AWS SDK for Rust"
documentation = "http://rusoto.github.io/rusoto/rusoto/index.html"
exclude = [".gitignore", ".travis.yml", "docgen.sh", "helpers/**/*", "codegen/**/*"]
keywords = ["AWS", "Amazon"]
license = "MIT"
name = "rusoto"
readme = "README.md"
repository = "https://github.com/rusoto/rusoto"
version = "0.24.0"
homepage = "https://www.rusoto.org/"

[badges]
travis-ci = { repository = "rusoto/rusoto", branch = "master" }
appveyor = { repository = "rusoto/rusoto", branch = "master" }

[build-dependencies]
rayon = "0.6.0"

[build-dependencies.rusoto_codegen]
default-features = false
path = "codegen"
version = ">= 0.8.0"

[dependencies]
chrono = "0.2.21"
hyper = "0.10.0"
log = "0.3.6"
md5 = "0.3.2"
rustc-serialize = "0.3.19"
serde = "1.0.2"
serde_derive = "1.0.2"
serde_json = "1.0.1"
xml-rs = "0.3"

[dependencies.rusoto_core]
path = "rusoto/core"
version = "0.24.0"

[dependencies.clippy]
optional = true
version = "0.0"

[dev-dependencies]
env_logger = "0.4.0"
rand = "^0.3.14"
time = "0.1.35"

[features]
all = [
		"acm",
	   	"autoscaling",
	   	"cloudformation",
	   	"cloudfront",
	   	"cloudhsm",
	   	"cloudsearch",
	   	"cloudtrail",
	   	"cloudwatch",
	   	"codecommit",
	   	"codedeploy",
	   	"codepipeline",
	   	"cognito-identity",
	   	"config",
	   	"datapipeline",
	   	"devicefarm",
	   	"directconnect",
	   	"ds",
	   	"dynamodb",
	   	"dynamodbstreams",
	   	"ec2",
	   	"ecr",
	   	"ecs",
	   	"elasticache",
	   	"elasticbeanstalk",
	   	"elastictranscoder",
	   	"elb",
	   	"elbv2",
	   	"emr",
	   	"events",
	   	"firehose",
	   	"iam",
	   	"importexport",
	   	"inspector",
	   	"iot",
	   	"kinesis",
	   	"kms",
	   	"lambda",
	   	"logs",
	   	"machinelearning",
	   	"marketplacecommerceanalytics",
	   	"opsworks",
	   	"redshift",
	   	"rds",
	   	"route53",
	   	"route53domains",
	   	"s3",
	   	"sdb",
	   	"ses",
	   	"sns",
	   	"sqs",
	   	"ssm",
	   	"storagegateway",
	   	"sts",
	   	"swf",
	   	"waf",
	   	"workspaces",
		"xray"
	]
acm = ["needs_serde_derive"]
autoscaling = []
cloudformation = []
cloudfront = []
cloudhsm = ["needs_serde_derive"]
cloudsearch = []
cloudtrail = ["needs_serde_derive"]
cloudwatch = []
codecommit = ["needs_serde_derive"]
codedeploy = ["needs_serde_derive"]
codepipeline = ["needs_serde_derive"]
cognito-identity = ["needs_serde_derive"]
config = ["needs_serde_derive"]
datapipeline = ["needs_serde_derive"]
default = []
devicefarm = ["needs_serde_derive"]
directconnect = ["needs_serde_derive"]
ds = ["needs_serde_derive"]
dynamodb = ["needs_serde_derive"]
dynamodbstreams = ["needs_serde_derive"]
ec2 = []
ecr = ["needs_serde_derive"]
ecs = ["needs_serde_derive"]
elasticache = []
elasticbeanstalk = []
elastictranscoder = ["needs_serde_derive"]
elb = []
elbv2 = []
emr = ["needs_serde_derive"]
events = ["needs_serde_derive"]
firehose = ["needs_serde_derive"]
iam = []
importexport = []
inspector = ["needs_serde_derive"]
iot = ["needs_serde_derive"]
kinesis = ["needs_serde_derive"]
kms = ["needs_serde_derive"]
lambda = ["needs_serde_derive"]
logs = ["needs_serde_derive"]
machinelearning = ["needs_serde_derive"]
marketplacecommerceanalytics = ["needs_serde_derive"]
needs_serde_derive = []
nightly-testing = ["clippy", "rusoto_codegen/nightly-testing", "rusoto_core/nightly-testing"]
opsworks = ["needs_serde_derive"]
redshift = []
rds = []
route53 = []
route53domains = ["needs_serde_derive"]
s3 = []
sdb = []
ses = []
sns = []
sqs = []
ssm = ["needs_serde_derive"]
storagegateway = ["needs_serde_derive"]
sts = []
swf = ["needs_serde_derive"]
unstable = []
waf = ["needs_serde_derive"]
workspaces = ["needs_serde_derive"]
xray = ["needs_serde_derive"]
packagea = [
	"acm",
	"autoscaling",
	"cloudformation",
	"cloudfront",
	"cloudhsm",
	"cloudsearch",
	"cloudtrail",
	"cloudwatch",
	"codecommit",
	"codedeploy",
	"codepipeline",
	"cognito-identity",
	"config",
	"datapipeline",
	"devicefarm",
	"directconnect",
	"ds",
	"dynamodb",
	"dynamodbstreams",
	"ec2",
	"ecr",
	"ecs",
	"elasticache",
	"elasticbeanstalk",
	"elastictranscoder",
	"elb",
	"elbv2",
	"emr",
	"events",
	"firehose"
]
packageb = [
	"iam",
	"importexport",
	"inspector",
	"iot",
	"kinesis",
	"kms",
	"lambda",
	"logs",
	"machinelearning",
	"marketplacecommerceanalytics",
	"opsworks",
	"redshift",
	"rds",
	"route53",
	"route53domains",
	"s3",
	"sdb",
	"ses",
	"sns",
	"sqs",
	"ssm",
	"storagegateway",
	"swf",
	"waf",
	"workspaces",
	"xray"
]