[package]
name = "rusoto"
version = "0.11.0"
authors = ["Anthony DiMarco <anthony.dimarco@dualspark.com>", "Matthew Mayer <matthewkmayer@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["AWS", "Amazon"]
description = "AWS SDK for Rust"
repository = "https://github.com/rusoto/rusoto"
documentation = "http://rusoto.github.io/rusoto/rusoto/index.html"
exclude = [".gitignore", ".travis.yml", "docgen.sh"]
build = "build.rs"

[build-dependencies.rusoto_codegen]
path = "codegen"

[dependencies]
xml-rs = "^0.1.26"
time = "^0.1.32"
openssl = "^0.7.1"
hyper = "^0.7.0"
url = "^0.2.37"
rustc-serialize = "^0.3.16"
regex = "^0.1.41"
chrono = "^0.2.16"
rust-crypto = "^0.2.34"
log = "^0.3.3"

[dev-dependencies]
env_logger = "*"

[features]
aws_integration = ["s3"]
s3 = []
kms = []
