[package]
authors = ["Anthony DiMarco <ocramida@gmail.com>", "Jimmy Cuadra <jimmy@jimmycuadra.com>", "Matthew Mayer <matthewkmayer@gmail.com>", "Nikita Pekin <contact@nikitapek.in>"]
description = "AWS SDK for Rust - AWS Elemental MediaConvert @ 2017-08-29"
documentation = "https://docs.rs/rusoto_mediaconvert"
keywords = ["AWS", "Amazon", "mediaconvert"]
license = "MIT"
name = "rusoto_mediaconvert"
readme = "README.md"
repository = "https://github.com/rusoto/rusoto"
version = "0.40.0"
homepage = "https://www.rusoto.org/"
edition = "2018"
exclude = ["test_resources/*"]

[build-dependencies]

[dependencies]
async-trait = "0.1"
bytes = "0.4"
serde = "1.0.2"
serde_derive = "1.0.2"
serde_json = "1.0.1"

[dependencies.futures-preview]
version = "0.3.0-alpha.19"

[dependencies.rusoto_core]
version = "0.40.0"
path = "../../core"
default-features = false
[dev-dependencies.rusoto_mock]
version = "0.40.0"
path = "../../../mock"

[features]
default = ["native-tls"]
native-tls = ["rusoto_core/native-tls"]
rustls = ["rusoto_core/rustls"]
