[package]
authors = [
    "Anthony DiMarco <ocramida@gmail.com>",
    "Jimmy Cuadra <jimmy@jimmycuadra.com>",
    "Matthew Mayer <matthewkmayer@gmail.com>",
    "Nikita Pekin <contact@nikitapek.in>"
]
description = "AWS SDK for Rust - Request Signing"
documentation = "https://docs.rs/rusoto_signature"
keywords = ["AWS", "Amazon"]
license = "MIT"
name = "rusoto_signature"
readme = "README.md"
repository = "https://github.com/rusoto/rusoto"
version = "0.41.0"
homepage = "https://www.rusoto.org/"
edition = "2018"

[badges]
appveyor = { repository = "matthewkmayer/rusoto", branch = "master" }
azure-devops = { project = "matthewkmayer/Rusoto", pipeline = "rusoto.rusoto", build="1" }

[features]
default = ["futures-01"]
futures-01 = ["tokio", "futures", "hyper"]
async-await = ["futures-preview", "hyper-alpha"]

[build-dependencies]
rustc_version = "0.2.1"

[dependencies]
bytes = "0.4.12"
futures-preview = { version = "=0.3.0-alpha.19", features = ["async-await"], optional = true }
hyper-alpha = { package = "hyper", features = ["unstable-stream"], version = "=0.13.0-alpha.4", optional = true }

futures = { version = "0.1.16", optional = true }
tokio = { version = "0.1.7", optional = true }
hyper = { version = "0.12", optional = true }

hmac = "0.7.1"
http = "0.1.17"
log = "0.4.1"
md5 = "0.6"
base64 = "0.10"
hex = "0.3"
serde = "1.0.2"
sha2 = "0.8.0"
time = "0.1.35"
percent-encoding = "2.1.0"

[dependencies.rusoto_credential]
path = "../credential"
version = "0.41"

[dev-dependencies]
serde_json = "1.0.2"
serde_test = "1.0.1"

