[package]
authors = ["Anthony DiMarco <ocramida@gmail.com>", "Jimmy Cuadra <jimmy@jimmycuadra.com>", "Matthew Mayer <matthewkmayer@gmail.com>", "Nikita Pekin <contact@nikitapek.in>"]
description = "AWS SDK for Rust - Amazon Simple Queue Service @ 2012-11-05"
documentation = "https://rusoto.github.io/rusoto/rusoto_sqs/index.html"
keywords = ["AWS", "Amazon", "sqs"]
license = "MIT"
name = "rusoto_sqs"
readme = "README.md"
repository = "https://github.com/rusoto/rusoto"
version = "0.33.0"
homepage = "https://www.rusoto.org/"

[build-dependencies]

[dependencies]
futures = "0.1.16"
serde_urlencoded = "0.5"
xml-rs = "0.7"

[dependencies.rusoto_core]
version = "0.33.0"
path = "../../core"
[dev-dependencies.rusoto_mock]
version = "0.26.0"
path = "../../../mock"
