[package]
authors = ["Anthony DiMarco <ocramida@gmail.com>", "Jimmy Cuadra <jimmy@jimmycuadra.com>", "Matthew Mayer <matthewkmayer@gmail.com>"]
build = "build.rs"
description = "Code generation library for Rusoto."
license = "MIT"
name = "rusoto_codegen"
repository = "https://github.com/rusoto/rusoto"
version = "0.1.0"

[build-dependencies.serde_codegen]
optional = true
version = "0.7.2"

[build-dependencies.syntex]
optional = true
version = "0.31.0"

[dependencies]
Inflector = "0.2.0"
regex = "0.1.65"
serde = "0.7.0"
serde_json = "0.7.0"

[dependencies.serde_codegen]
optional = true
version = "0.7.2"

[dependencies.serde_macros]
optional = true
version = "0.7.2"

[dependencies.syntex]
optional = true
version = "0.31.0"

[features]
default = ["with-syntex"]
nightly = ["serde_macros"]
with-syntex = ["serde_codegen", "syntex"]
