name: CI

on: [push, pull_request]

jobs:
  unit_and_integration_tests:
    name: Unit and integration tests
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        rust: [stable, beta, nightly]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 5
    - name: Set up Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Run unit tests
      shell: bash
      run: RUST_VERSION=${{ matrix.rust }} make unit_test
    - name: Cargo check integration tests
      shell: bash
      run: RUST_VERSION=${{ matrix.rust }} make check_integration_test
  rustls_unit_tests:
    name: Rustls unit tests
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        rust: [stable, beta, nightly]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 5
    - name: Set up Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Run unit tests with rustls
      shell: bash
      run: RUST_VERSION=${{ matrix.rust }} make rustls_unit_test
  crate_gen:
    name: Crate generation
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive
        fetch-depth: 5
    - name: Set up Rust
      uses: hecrj/setup-rust-action@v1
      with:
        components: rustfmt
    - name: Generate crates
      run: make generate
  skeptic:
    name: Skeptic tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 5
    - name: Set up Rust
      uses: hecrj/setup-rust-action@v1
    - name: Skeptic Test
      run: make skeptical
